version: "3.7"
services:
  cms:
    build: ./cms
    depends_on:
      - mongo
    # ports:
    #   - 1337:1337
    environment:
      - DATABASE_HOST=mongo
      - DATABASE_NAME=blackcoffeecms
  users:
    build: ./users
    restart: on-failure
    env_file:
      - ./users/.env
    depends_on:
      - postgres
  graphql:
    build: ./graphql
    env_file:
      - ./graphql/.env
    depends_on:
      - cms
    ports:
      - 4000:4000
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=usersdb
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: